django_social_media_project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.HomePage.as_view(), name='home'),
    url(r'^accounts/',include('accounts.urls', namespace='accounts')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^test/$',
        views.TestPage.as_view(),
        name='test'),
    url(r'^thanks/$',
        views.ThanksPage.as_view(),
        name='thanks'),
    url(r'^groups/',include('groups.urls',namespace='groups')),
    url(r'^posts/',include('posts.urls',namespace='posts')),
]

groups/urls.py
from django.conf.urls import url
from . import views

app_name = 'groups'

urlpatterns = [
    url(r'^$',views.ListGroup.as_view(),name='all'),
    url(r'new/$',views.CreateGroup.as_view(),name='create'),
    url(r'posts/in/(?P<slug>[\w]+)/$',views.Singlegroup.as_view(),name='single'),
    url(r'join/(?P<slug>[\w]+)/$',views.JoinGroup.as_view(),name='join'),
    url(r'leave/(?P<slug>[\w]+)/$',views.LeaveGroup.as_view(),name='leave'),

]

posts/urls.py
from django.conf.urls import url

from . import views

app_name='posts'

urlpatterns = [
    url(r'^$',views.PostList.as_view(),name='all'),
    url(r'new/$',views.CreatePost.as_view(),name='create'),
    url(r'by/(?P<username>[-\w]+)',views.UserPosts.as_view(),name='for_user'),
    url(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.PostDetail.as_view(),name='single'),
    url(r'delete/(?P<pk>\d+)/$',views.DeletePost.as_view(),name='delete'),
]

groups/models.py
from django.db import models
from django.utils.text import slugify
from django.core.urlresolvers import reverse
import misaka

# Create your models here.
from django.contrib.auth import get_user_model
User = get_user_model()

from django import template
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User,through="GroupMember")

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("groups:single", kwargs={"slug": self.slug})
    
    class Meta:
        ordering = ['name']

class GroupMember(models.Model):
    group = models.ForeignKey(Group,related_name='memberships')
    user = models.ForeignKey(User,related_name='user_groups')

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group','user')

groups/views.py
from django.shortcuts import render
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.core.urlresolvers import reverse
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.views.generic import (
                                    CreateView,
                                    UpdateView,
                                    DeleteView,
                                    ListView,
                                    DetailView,
                                    RedirectView,
                                )
from groups.models import Group,GroupMember
from . import models

# Create your views here.
class CreateGroup(LoginRequiredMixin,CreateView):
    fields = ('name','description')
    model = Group

class Singlegroup(DetailView):
    model = Group

class ListGroup(ListView):
    model = Group

class JoinGroup(LoginRequiredMixin,RedirectView):
    
    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single',kwargs={
            'slug': self.kwargs.get('slug')
        })

    def get(self,request,*args,**kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)
        except IntegrityError:
            messages.warning(self.request,'Warning!!! already a member')
        else:
            messages.success(self.request,'You are nowa member')

        return super().get(request,*args,**kwargs)

class LeaveGroup(LoginRequiredMixin,RedirectView):
    
    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single',kwargs={
            'slug': self.kwargs.get('slug')
        })

    def get(self,request,*args,**kwargs):

        try:
            membership = GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get('slug')
            ).get()
        except GroupMember.DoesNotExist:
            messages.warning(self.request,"Sorry, you aren't in this group")
        else:
            membership.delete()
            messages.success(self.request,'You have left the group')
        return super().get(request,*args,**kwargs)

groups/templates/groups/group_base.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <div class="row">
    {% block pregroup %}{% endblock %}
    {% block group_content %}{% endblock %}
    {% block postgroup %}{% endblock %}
  </div>
</div>
{% endblock %}

groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}
{% block pregroup %}
<div class="col-12">
  <h1>
    {{group.name}}
  </h1>

  <h3>
    Members: {{ group.members.count }}
  </h3>

  <div>
    {% if user in group.members.all %}
      <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-lg btn-fill btn-warning"><i class="fas fa-times"></i> Leave group</a>
    {% else %}
      <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-lg btn-fill btn-default"><i class="fas fa-check-circle"></i> Join Group</a>
    {% endif %}
  </div>
</div>
{% endblock %}

{% block group_content %}
<div class="col-xs-12 col-sm-6 col-8">
  {% if group.posts.count == 0 %}
    <h3>No post in this group</h3>
  {% else %}
    {% for post in group.posts.all %}
      {% include "posts/_post.html" %}
    {% endfor %}
  {% endif %}
</div>
{% endblock %}

groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}
{% load bootstrap4 %}

{% block group_content %}
<div class="jumbotron"></div>
  <h4>Create a group</h4>
  <form class="form" method="POST" action="{% url 'groups:create' %}" >
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary">Create Group</button>
    {% endbuttons %}
  </form>
</div>
{% endblock %}

groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}
<div class="col-xs-12 col-sm-6 col-4">
  {% if user.is_authenticated %}
    <h2>Welcome back!!!! <a href="{% url 'posts:for_user' username=user.username %}">@{{user.username}}</a></h2>
  {% endif %}
  <h3>groups</h3>
  <p>Welcome to groups page</p>
  {% if user.is_authenticated %}
    <a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning"><i class="fas fa-check-circle"></i>Create Group</a>
  {% endif %}
</div>
{% endblock %}
{% block group_content %}
<div class="col-xs-12 col-sm-6 col-8">
  {% for group in object_list %}
  <a href="{% url 'groups:single' slug=group.slug %}"><h3>{{group.name}}</h3></a>
  <div class="container-fluid">
    <p>{{group.description_html|safe}}</p>
    <div class="row">
      <div class="col-md=4">
        <span class="badge">{{group.members.count}}</span> member{{group.members.count|pluralize}}
      </div>
      <div class="col-md=4">
        <span class="badge">{{group.posts.count}}</span> post{{group.posts.count|pluralize}}
      </div>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}