django_social_media_project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.HomePage.as_view(), name='home'),
    url(r'^accounts/',include('accounts.urls', namespace='accounts')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^test/$',
        views.TestPage.as_view(),
        name='test'),
    url(r'^thanks/$',
        views.ThanksPage.as_view(),
        name='thanks'),
    url(r'^groups/',include('groups.urls',namespace='groups')),
    url(r'^posts/',include('posts.urls',namespace='posts')),
]

posts/urls.py
from django.conf.urls import url

from . import views

app_name='posts'

urlpatterns = [
    url(r'^$',views.PostList.as_view(),name='all'),
    url(r'new/$',views.CreatePost.as_view(),name='create'),
    url(r'by/(?P<username>[-\w]+)',views.UserPosts.as_view(),name='for_user'),
    url(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.PostDetail.as_view(),name='single'),
    url(r'delete/(?P<pk>\d+)/$',views.DeletePost.as_view(),name='delete'),
]

posts/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.conf import settings
from django.contrib.auth import get_user_model

import misaka

# Create your models here.
from groups.models import Group

User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User,related_name='posts')
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group,related_name='posts',null=True,blank=True)

    def __str__(self):
        return self.message

    def save(self,*args,**kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('posts:single',kwargs={
            'username': self.user.username,
            'pk': self.pk
        })

    class Meta:
        ordering = ['-created_at']
        unique_together = ['user','message']

posts/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.http import Http404
from django.views.generic import (ListView,DetailView,CreateView,DeleteView)
from braces.views  import SelectRelatedMixin
from django.contrib.auth import get_user_model
from django.contrib import messages
from .models import Post

# Create your views here.
User = get_user_model()

class PostList(SelectRelatedMixin,ListView):
    model = Post
    select_related = ('user','group')

class UserPosts(ListView):
    model = Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()
        
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] =  self.post_user
        return context

class PostDetail(SelectRelatedMixin,DetailView):
    model = Post
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))

class CreatePost(LoginRequiredMixin,SelectRelatedMixin,CreateView):
    fields = ('message', 'group')
    model = Post

    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)
    
class DeletePost(LoginRequiredMixin,SelectRelatedMixin,DeleteView):
    model = Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self,*args,**kwargs):
        messages.success(self.request,'Post Deleted')
        return super().delete(*args,**kwargs)

posts/templates/posts/_post.html
<div>
  <h3>
    {{post.message_html|safe}}
  </h3>
  <div>
    <h5>
    <span>
      <a href="{% url 'posts:for_user' username=post.user.username %}">@{{post.user.username}}</a>
    </span>
    <time>
      <a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{post.created_at}}</a>
    </time>
    </h5>

    <div>
      {% if user.is_authenticated and post.user == user %}
        <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-simple">
          <i aria-hidden="true"></i>
          <span class="text-danger icon-label">Delete</span>
        </a>
      {% endif %}
    </div>
  </div>
</div>

posts/templates/posts/post_base.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  <div class="row">
    {% block pre_post %}{% endblock %}
    {% block post_content %}{% endblock %}
    {% block post_post %}{% endblock %}
  </div>
</div>

{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends 'posts/post_base.html' %}

{% block post_content %}

<h2>Are you sre you want to delete this post?</h2>

{% include 'posts/_post.html' with post=object hide_delete=True %}

<form method="POST">
  {% csrf_token %}
  <input type="submit" value="Delete" class="btn btn-large btn-danger" />
  <a class="btn btn-simple btn-default" href="{% url 'posts:single' username=user.username pk=object.pk %}">Cancel</a>
</form>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'posts/post_base.html' %}

{% block post_content %}
<div class="col-w75">
  {%- include 'posts/_post.html' -%}
</div>

{% endblock %}

posts/templates/posts/post_form.html
{% extends 'posts/post_base.html' %}
{% load bootstrap4 %}

{% block post_content %}
<h3>Create a post</h3>
<form method="POST"
      action="{% url 'posts:create' %}">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button type="submit" class="btn btn-primary">Post</button>
  {% endbuttons %}
</form>
{% endblock %}

posts/templates/posts/post_list.html
{% extends 'posts/post_base.html' %}

{% block pre_post %}
<div class="col-w25">
  {% if request.user.is_authenticated %}
    <div class="card">
      <div class="card-body">
        <div class="card-header">Your groups</div>
        <h5 class="card-title"></h5>
        <p class="card-text">
          <ul>
            {% for member_group in get_user_groups %}
              <li><a href="{% url 'groups:single' slug=member_group.group.slug %}">{{ member_group.group.name }}</a></li>
            {% endfor %}
          </ul>
        </p>
      </div>
    </div>
  {% endif %}
  <div class="card">
    <div class="card-body">
      <div class="card-header">All Groups</div>
      <h5 class="card-title"></h5>
      <p class="card-text">
        <ul>
          {% for other_group in get_other_groups %}
          <li><a href="{% url 'groups:single' slug=other_group.group.slug %}">{{ other_group.group.name }}</a></li>
          {% endfor %}
        </ul>
      </p>
    </div>
  </div>
</div>
{% endblock %}

{% block post_post %}
<div class="col-w75">
  {% for post in post_list %}
    {% include 'posts/_post.html' %}
  {% endfor %}
</div>
{% endblock %}

posts/templates/posts/user_post_list.html
{% extends 'posts/post_base.html' %}

{% block pre_post %}
<div class="col-w25">
  <h2>@{{ post_user.username }}</h2>
</div>
{% endblock %}


{% block post_content %}
<div class="col-w75">
  {% for post in post_list %}
    {% include 'posts/_post.html' %}
  {% endfor %}
</div>
{% endblock %}